version: "3.7"

services: 
  contact:
    container_name: contact
    restart: always
    build: ./contact
    environment: 
      - PORT=3000
    ports: 
      - "3000:3000"
    links:
      - mongo
      - redis
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "2017:2017"
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379