version: "3.5"

services: 
  app:
    container_name: contact
    restart: always
    build: ./contact
    environment: 
      - PORT=3000
    ports: 
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"