FROM node:14

# Create app directory
WORKDIR /usr/src/app
RUN chmod -R 777 /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./
RUN npm install

COPY ./lib ./lib


# Bundle app source
# COPY . .

RUN npm run build

# WORKDIR ./dist

EXPOSE 3000
CMD npm start